name: Git-Flow Enforcer
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  git-flow-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verify git flow
        run: bash .github/workflows/check-git-flow.sh ${{ github.head_ref }} ${{ github.base_ref }}

  # branch-check-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Test branch names
  #       run: |
  #         bash .github/workflows/check-git-flow.sh feature/valid-branch-name develop test
  #         bash .github/workflows/check-git-flow.sh release/valid-branch-name develop test
  #         bash .github/workflows/check-git-flow.sh hotfix/valid-branch-name main test
  #         bash .github/workflows/check-git-flow.sh invalid-branch-name invalid-branch test